### ISSUE TITLE
Failure in loading Octagon OSC file

### ISSUE THREAD

**Issue by ygrayson** [SainsburyWellcomeCentre/aeon_mecha#181]
Hello,

As I was trying to load the Octagon OSC files with the following lines:

`from aeon.schema.dataset import octagon01`
`root = "/ceph/aeon/aeon/data/raw/OCTAGON01/conf1/"`
`slices = api.load(root, reader=octagon01.OSC.Slice, epoch='2022-10-28T15-22-42')`

The following error poped up:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/33047668/207092914-b03e4aa3-e351-4c87-8755-65b02a1eb93d.png">

This does not present any problem while loading `epoch='2022-08-05T08-54-05'`. I checked the CSV file and it seems like the later epoch has one more colomn than the earlier epoch, which I think could be the cause of this bug.

Thanks.

**Comment by jkbhagatio** [comment]
Closing this as was fixed with a column reordering on writing out the csv file
