### ISSUE TITLE
Metadata.yml and other unchunked files cannot be filtered by time range

### ISSUE THREAD

**Issue by lochhh** [SainsburyWellcomeCentre/aeon_mecha#186]
As ``chunk_key`` here returns the epoch timestamp directly
https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/bf96b6346f272dc3a7d91ea636e5f93634dbeeae/aeon/io/api.py#L37-L46

and the ``chunk_range`` only includes hourly timestamps, files that do not have hourly timestamps  in their names (e.g. Metadata.yml) are removed by the filter.
https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/bf96b6346f272dc3a7d91ea636e5f93634dbeeae/aeon/io/api.py#L118-L119

MWE:
```python
import aeon.io.api as aeon
from aeon.schema.dataset import exp02

root = "/ceph/aeon/aeon/data/raw/AEON3/presocial0.1/"
aeon.load(root, exp02.Metadata, start=pd.Timestamp("2023-02-24 00:00:00"), end=pd.Timestamp("2023-02-26 00:00:00"))
```

**Comment by glopesdev** [comment]
@lochhh can you test if this version makes any difference? 

https://github.com/SainsburyWellcomeCentre/aeon_mecha/commit/5ba19c1f0b74834a377c771dd725437dba3228d5

**Comment by glopesdev** [comment]
Ok, nevermind the above, I now understand the issue. I will rename the title for clarity, the problem is that time filtering relies on chunks being timestamped, and `Metadata.yml` files are not chunked at all, so in this case we would probably have to rely on filtering on epochs.
