### ISSUE TITLE
Wheel build for Datajoint failing on macOS 12 using mamba

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#249]
See here: https://github.com/SainsburyWellcomeCentre/aeon_mecha/actions/runs/6004715050/job/16285882719#step:3:1161

@JaerongA noted that it's attempting to install datajoint from @ttngu207 's fork

**Comment by ttngu207** [comment]
The one known potential cause for this issue has been resolved. Please try running this again
