### ISSUE TITLE
Timestamps in DJ tables don't align with the python api

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#25]
Thinh has set it so DJ truncates timestamps after 3 decimals to save on storage with the precision. Maybe in python we should truncate timestamps as well? Or DJ should not truncate. But the behaviour should be consistent.

**Comment by jkbhagatio** [comment]
This was solved at the time of this comment:

> Since MySQL can store datetimes with microsecond precision, we will use microsecond timestamps both on DJ tables and in the python api

**Comment by jerlich** [comment]
I don't know how many rows per day you are inserting (like if it is just once per chunk it isn't that bad), but storage is not free, so if you can reduce your storage without compromising on the data, it is encouraged (speaking from the IT steering committee). You should assume that data storage costs about £50 per TB per year.
