### ISSUE TITLE
no .profile file

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_mecha#254]
Cannot locate the .profile file in my hpc user folder.
https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/eb306bd21e0afc202ea756ed4db02593dc96f2a0/docs/env_setup/remote/miniconda_conda_remote_setup.md

**Comment by jkbhagatio** [comment]
I will change the wording now to make this more clear to create a `.profile` if the file doesn't already exists. 

I'll create a new branch called `update_docs` where I put this (and other things you notice in the next couple weeks @Dario55 ) and merge this after I get back to London on Oct 2
