### ISSUE TITLE
SAB presentation 2023

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_mecha#258]
- [x] 1)get the ephys rig up and running to collect a video with the remote controlled car (ideally this would include both the slider motor and the rotary joint). I can help with this, I’ll be always in a part for Tuesday afternoon and Wed morning André Almeida (guest),Goncalo Lopes (guest)are you guys free today/tomorrow?
- [x] 2)Get a reader for the scale in AEON3. I could not get exp0.2 to work with data from  experiment 0.2 nor 0.3
- [ ] 3)Andrew Erskine (guest) I would please need a slide about the feeder testing. It would be enough a screenshot of the camera video, a screenshot of the zoomed in part of the wheel with the detected  pellet highlighted, and the numbers of correct, failure, double etc for one session (the first you did will work).
- [x] 4)A way to read the RFID and multianimal tracking data streams (Bhagat, Jai we can discuss when we meet today)
- [x] 5) Aquire a video of escape trial

**Comment by jkbhagatio** [comment]
@Dario55 can you close this if done? Or if there is anything lingering that wasn't completed for this presentation that you still think is important, can you make another issue?

**Comment by Dario55** [comment]
Fine to close
