### ISSUE TITLE
Arbitrary Devices can't be created - pattern name must be shared across all Readers within a Device

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#297]
Currently on `Device` instantiation, a helper function is called to group Reader objects together in a dictionary that goes into an attribute in the Device object, and helper function sets a pattern prefix for all Reader objects it contains. 

I'd suggest instead to make it so that it's not necessary that the same pattern prefix gets passed to all a Device object's Reader objects. This could be accomplished by setting a default `None` pattern arg for the helper function

**Comment by glopesdev** [comment]
The current schema for devices assumes that all files inside a `Device` start with a prefix which is equal to the name of the device, at the folder level. Assuming we don't want to change this convention, then this behavior would be by design.
