### ISSUE TITLE
Should change `class` column name returned in PoseReader

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#308]
`class` is a keyword in Python and so it makes it so that you can't do the following:

```
subjects_positions = aeon.load(root, social01.Camera.CameraTopPos, start_time, end_time)
subjects_positions.class
```

> SyntaxError: invalid syntax

**Comment by ttngu207** [comment]
Yes, I noticed this too.
I can make this change. Do you have a preference on what to replace `class` with? I suggest `pose_identity` for consistency.
