### ISSUE TITLE
Sleap model dir needs to be saved to metadata.yml

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#328]
To do the subject int2str conversion, you need to know the model dir. Previously I was pulling this from the metadata file. For recent epochs, it's not available in the metadata.yml as it is being passed in as an argument to the bonsai exp workflow shortcut, and is not being logged within bonsai. The reason it is important to have is because this info is not directly available to someone who is just working with the schema.

**Comment by ttngu207** [comment]
Yes, that'd be much better, this is the current implementation in SLEAP ingestion:
https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/e9c4eabf9708952a4054defee76f01059e07f2db/aeon/dj_pipeline/tracking.py#L179

**Comment by glopesdev** [comment]
The most efficient solution to convert class IDs into strings might be to do it inside the PoseReader where the JSON metadata file for the model is already accessed to retrieve part labels, etc.
