### ISSUE TITLE
No SLEAP data found in some chunks

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#354]
There are 131 chunks without SLEAP data - I'm not sure if there's a bug in the loader or those chunks actually do not have SLEAP data

The code to do the loading is below

```
data_dirs = [PosixPath('/ceph/aeon/aeon/data/raw/AEON3/social0.1')]

pose_data = api.load(
    root=data_dirs,
    reader=social01.CameraTop.Pose,
    start=pd.Timestamp(chunk_start),
    end=pd.Timestamp(chunk_end),
)
```

[empty_pose_df.csv](https://github.com/SainsburyWellcomeCentre/aeon_mecha/files/15044682/empty_pose_df.csv)

**Comment by jkbhagatio** [comment]
Do you have example start and end timestamps for these? All social0.1 and social0.2 data _should_ have position tracking

**Comment by ttngu207** [comment]
"",experiment_name,chunk_start,device_serial_number,chunk_end,spinnaker_video_source_name
0,social0.1-aeon3,2023-11-22 11:00:00,23032909,2023-11-22 12:00:00,CameraTop
1,social0.1-aeon3,2023-11-22 12:00:00,23032909,2023-11-22 13:00:00,CameraTop
2,social0.1-aeon3,2023-11-22 13:00:00,23032909,2023-11-22 14:00:00,CameraTop
3,social0.1-aeon3,2023-11-22 14:00:00,23032909,2023-11-22 15:00:00,CameraTop
4,social0.1-aeon3,2023-11-22 15:00:00,23032909,2023-11-22 16:00:00,CameraTop
5,social0.1-aeon3,2023-11-22 16:00:00,23032909,2023-11-22 17:00:00,CameraTop
6,social0.1-aeon3,2023-11-22 17:00:00,23032909,2023-11-22 18:00:00,CameraTop
7,social0.1-aeon3,2023-11-22 18:00:00,23032909,2023-11-22 19:00:00,CameraTop
8,social0.1-aeon3,2023-11-22 19:00:00,23032909,2023-11-22 20:00:00,CameraTop
9,social0.1-aeon3,2023-11-22 20:00:00,23032909,2023-11-22 21:00:00,CameraTop
10,social0.1-aeon3,2023-11-22 21:00:00,23032909,2023-11-22 22:00:00,CameraTop
11,social0.1-aeon3,2023-11-22 22:00:00,23032909,2023-11-22 23:00:00,CameraTop
12,social0.1-aeon3,2023-11-22 23:00:00,23032909,2023-11-23 00:00:00,CameraTop
13,social0.1-aeon3,2023-11-23 00:00:00,23032909,2023-11-23 01:00:00,CameraTop
14,social0.1-aeon3,2023-11-23 01:00:00,23032909,2023-11-23 02:00:00,CameraTop
15,social0.1-aeon3,2023-11-23 02:00:00,23032909,2023-11-23 03:00:00,CameraTop
16,social0.1-aeon3,2023-11-23 03:00:00,23032909,2023-11-23 04:00:00,CameraTop
17,social0.1-aeon3,2023-11-23 04:00:00,23032909,2023-11-23 05:00:00,CameraTop
18,social0.1-aeon3,2023-11-23 05:00:00,23032909,2023-11-23 06:00:00,CameraTop
19,social0.1-aeon3,2023-11-23 06:00:00,23032909,2023-11-23 07:00:00,CameraTop
20,social0.1-aeon3,2023-11-23 07:00:00,23032909,2023-11-23 08:00:00,CameraTop
21,social0.1-aeon3,2023-11-23 08:00:00,23032909,2023-11-23 09:00:00,CameraTop
22,social0.1-aeon3,2023-11-23 09:00:00,23032909,2023-11-23 10:00:00,CameraTop
23,social0.1-aeon3,2023-11-23 10:00:00,23032909,2023-11-23 11:00:00,CameraTop
24,social0.1-aeon3,2023-11-23 11:00:00,23032909,2023-11-23 12:00:00,CameraTop
25,social0.1-aeon3,2023-11-23 12:00:00,23032909,2023-11-23 13:00:00,CameraTop
26,social0.1-aeon3,2023-11-23 13:00:00,23032909,2023-11-23 14:00:00,CameraTop
27,social0.1-aeon3,2023-11-23 14:00:00,23032909,2023-11-23 15:00:00,CameraTop
28,social0.1-aeon3,2023-11-23 15:00:00,23032909,2023-11-23 16:00:00,CameraTop
29,social0.1-aeon3,2023-11-23 16:00:00,23032909,2023-11-23 16:55:23,CameraTop
30,social0.1-aeon3,2023-11-23 16:55:23,23032909,2023-11-23 17:00:00,CameraTop
31,social0.1-aeon3,2023-11-23 17:00:00,23032909,2023-11-23 18:00:00,CameraTop
32,social0.1-aeon3,2023-11-23 18:00:00,23032909,2023-11-23 19:00:00,CameraTop
33,social0.1-aeon3,2023-11-23 19:00:00,23032909,2023-11-23 20:00:00,CameraTop
34,social0.1-aeon3,2023-11-23 20:00:00,23032909,2023-11-23 21:00:00,CameraTop
35,social0.1-aeon3,2023-11-23 21:00:00,23032909,2023-11-23 22:00:00,CameraTop
36,social0.1-aeon3,2023-11-23 22:00:00,23032909,2023-11-23 23:00:00,CameraTop
37,social0.1-aeon3,2023-11-23 23:00:00,23032909,2023-11-24 00:00:00,CameraTop
38,social0.1-aeon3,2023-11-24 00:00:00,23032909,2023-11-24 01:00:00,CameraTop
39,social0.1-aeon3,2023-11-24 01:00:00,23032909,2023-11-24 02:00:00,CameraTop
40,social0.1-aeon3,2023-11-24 02:00:00,23032909,2023-11-24 03:00:00,CameraTop
41,social0.1-aeon3,2023-11-24 03:00:00,23032909,2023-11-24 04:00:00,CameraTop
42,social0.1-aeon3,2023-11-24 04:00:00,23032909,2023-11-24 05:00:00,CameraTop
43,social0.1-aeon3,2023-11-24 05:00:00,23032909,2023-11-24 06:00:00,CameraTop
44,social0.1-aeon3,2023-11-24 06:00:00,23032909,2023-11-24 07:00:00,CameraTop
45,social0.1-aeon3,2023-11-24 07:00:00,23032909,2023-11-24 08:00:00,CameraTop
46,social0.1-aeon3,2023-11-24 08:00:00,23032909,2023-11-24 09:00:00,CameraTop
47,social0.1-aeon3,2023-11-24 09:00:00,23032909,2023-11-24 10:00:00,CameraTop
48,social0.1-aeon3,2023-11-24 10:00:00,23032909,2023-11-24 11:00:00,CameraTop
49,social0.1-aeon3,2023-11-24 11:00:00,23032909,2023-11-24 12:00:00,CameraTop
50,social0.1-aeon3,2023-11-24 12:00:00,23032909,2023-11-24 13:00:00,CameraTop
51,social0.1-aeon3,2023-11-24 13:00:00,23032909,2023-11-24 13:25:03,CameraTop
52,social0.1-aeon3,2023-11-24 13:25:03,23032909,2023-11-24 14:00:00,CameraTop
53,social0.1-aeon3,2023-11-24 14:00:00,23032909,2023-11-24 15:00:00,CameraTop
54,social0.1-aeon3,2023-11-24 15:00:00,23032909,2023-11-24 16:00:00,CameraTop
55,social0.1-aeon3,2023-11-24 16:00:00,23032909,2023-11-24 17:00:00,CameraTop
56,social0.1-aeon3,2023-11-24 17:00:00,23032909,2023-11-24 18:00:00,CameraTop
57,social0.1-aeon3,2023-11-24 18:00:00,23032909,2023-11-24 19:00:00,CameraTop
58,social0.1-aeon3,2023-11-24 19:00:00,23032909,2023-11-24 20:00:00,CameraTop
59,social0.1-aeon3,2023-11-24 20:00:00,23032909,2023-11-24 21:00:00,CameraTop
60,social0.1-aeon3,2023-11-24 21:00:00,23032909,2023-11-24 22:00:00,CameraTop
61,social0.1-aeon3,2023-11-24 22:00:00,23032909,2023-11-24 23:00:00,CameraTop
62,social0.1-aeon3,2023-11-24 23:00:00,23032909,2023-11-25 00:00:00,CameraTop
63,social0.1-aeon3,2023-11-25 00:00:00,23032909,2023-11-25 01:00:00,CameraTop
64,social0.1-aeon3,2023-11-25 01:00:00,23032909,2023-11-25 02:00:00,CameraTop
65,social0.1-aeon3,2023-11-25 02:00:00,23032909,2023-11-25 03:00:00,CameraTop
66,social0.1-aeon3,2023-11-25 03:00:00,23032909,2023-11-25 04:00:00,CameraTop
67,social0.1-aeon3,2023-11-25 04:00:00,23032909,2023-11-25 05:00:00,CameraTop
68,social0.1-aeon3,2023-11-25 05:00:00,23032909,2023-11-25 06:00:00,CameraTop
69,social0.1-aeon3,2023-11-25 06:00:00,23032909,2023-11-25 07:00:00,CameraTop
70,social0.1-aeon3,2023-11-25 07:00:00,23032909,2023-11-25 08:00:00,CameraTop
71,social0.1-aeon3,2023-11-25 08:00:00,23032909,2023-11-25 09:00:00,CameraTop
72,social0.1-aeon3,2023-11-25 09:00:00,23032909,2023-11-25 10:00:00,CameraTop
73,social0.1-aeon3,2023-11-25 10:00:00,23032909,2023-11-25 11:00:00,CameraTop
74,social0.1-aeon3,2023-11-25 11:00:00,23032909,2023-11-25 12:00:00,CameraTop
75,social0.1-aeon3,2023-11-25 12:00:00,23032909,2023-11-25 13:00:00,CameraTop
76,social0.1-aeon3,2023-11-25 13:00:00,23032909,2023-11-25 14:00:00,CameraTop
77,social0.1-aeon3,2023-11-25 14:00:00,23032909,2023-11-25 15:00:00,CameraTop
78,social0.1-aeon3,2023-11-25 15:00:00,23032909,2023-11-25 16:00:00,CameraTop
79,social0.1-aeon3,2023-11-25 16:00:00,23032909,2023-11-25 17:00:00,CameraTop
80,social0.1-aeon3,2023-11-25 17:00:00,23032909,2023-11-25 18:00:00,CameraTop
81,social0.1-aeon3,2023-11-25 18:00:00,23032909,2023-11-25 19:00:00,CameraTop
82,social0.1-aeon3,2023-11-25 19:00:00,23032909,2023-11-25 20:00:00,CameraTop
83,social0.1-aeon3,2023-11-25 20:00:00,23032909,2023-11-25 21:00:00,CameraTop
84,social0.1-aeon3,2023-11-25 21:00:00,23032909,2023-11-25 22:00:00,CameraTop
85,social0.1-aeon3,2023-11-25 22:00:00,23032909,2023-11-25 23:00:00,CameraTop
86,social0.1-aeon3,2023-11-25 23:00:00,23032909,2023-11-26 00:00:00,CameraTop
87,social0.1-aeon3,2023-11-26 00:00:00,23032909,2023-11-26 01:00:00,CameraTop
88,social0.1-aeon3,2023-11-26 01:00:00,23032909,2023-11-26 02:00:00,CameraTop
89,social0.1-aeon3,2023-11-26 02:00:00,23032909,2023-11-26 03:00:00,CameraTop
90,social0.1-aeon3,2023-11-26 03:00:00,23032909,2023-11-26 04:00:00,CameraTop
91,social0.1-aeon3,2023-11-26 04:00:00,23032909,2023-11-26 05:00:00,CameraTop
92,social0.1-aeon3,2023-11-26 05:00:00,23032909,2023-11-26 06:00:00,CameraTop
93,social0.1-aeon3,2023-11-26 06:00:00,23032909,2023-11-26 07:00:00,CameraTop
94,social0.1-aeon3,2023-11-26 07:00:00,23032909,2023-11-26 08:00:00,CameraTop
95,social0.1-aeon3,2023-11-26 08:00:00,23032909,2023-11-26 09:00:00,CameraTop
96,social0.1-aeon3,2023-11-26 09:00:00,23032909,2023-11-26 10:00:00,CameraTop
97,social0.1-aeon3,2023-11-26 10:00:00,23032909,2023-11-26 11:00:00,CameraTop
98,social0.1-aeon3,2023-11-26 11:00:00,23032909,2023-11-26 12:00:00,CameraTop
99,social0.1-aeon3,2023-11-26 12:00:00,23032909,2023-11-26 13:00:00,CameraTop

**Comment by ttngu207** [comment]
After troubleshooting with @jkbhagatio this is due to the different patterns of SLEAP file for chunks before/after `2023-12-01`
- `CameraTop_test-node0*`
- `CameraTop_test-node1*`

**Comment by ttngu207** [comment]
Problem solved - closing this issue
