### ISSUE TITLE
Multiple patch rates and offsets found in one patch for one block

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#358]
In Block level analysis - we expect only one patch rate and patch offset for each patch.

However, in some blocks, there are multiple values found. We need to determine which value to use from the multiple values.

See attached csv file for blocks with the errors

[df.csv](https://github.com/SainsburyWellcomeCentre/aeon_mecha/files/15112185/df.csv)

**Comment by jkbhagatio** [comment]
@glopesdev it seems like this is probably the PatchState updating before the BlockState. In what cases can this occur?

And I guess for analysis for social02, we're fine just keeping the first rate (in blocks with >1 rate) as the "true" rate

**Comment by jerlich** [comment]
Is this a bug? At the block transition we don't change the rate until the next pellet delivery. 

The csv only has the block times. Can you give an example the list of the rates in one block?

**Comment by jkbhagatio** [comment]
These double 0's still occur in BlockState, but guess the second 0 can just kind of be safely ignored? @glopesdev

**Comment by jkbhagatio** [comment]
> These double 0's still occur in BlockState, but guess the second 0 can just kind of be safely ignored? 

yes.
