### ISSUE TITLE
Add threshold-specific pellet delivery timestamps as dj table

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#382]
This should have the timestamp a pellet was delivered (from beambreak ideally) and the corresponding threshold value

**Comment by ttngu207** [comment]
Add here the latest logic discussed and finalized for this procedure

1. Get all patch state update timestamps: let's call these events "A"
2. Remove all "A" events near manual pellet delivery events (so we don't include manual pellet delivery events in downstream analysis)
3. For the remaining "A" events, find the nearest delivery event within 1s: for this delivery event, check if there are any repeat delivery events within 0.5 seconds - take the last of these as the pellet delivery timestamp (discard all "A" events that don't have such a corresponding delivery event)
4. Now for these 'clean' "A" events, go back in time to the SECOND preceding pellet threshold value: this is the threshold value for this pellet delivery (as seen in this image we discussed before)
![MicrosoftTeams-image](https://github.com/user-attachments/assets/8cd25147-2bd8-4113-afdf-0331ca75c213)
