### ISSUE TITLE
patch location changing across sessions

### ISSUE THREAD

**Issue by joacorapela** [SainsburyWellcomeCentre/aeon_mecha#40]
In the Dashboard I set the coordinates of Patch2 to match the location where mouse BAA-1099793, in session 2021-09-08T07:44:51, between 9530 and 9960 seconds, was working in the wheel.

But when I observe the same mouse in the earlier session 2021-06-18T08:24:18, between 12280 and 12550 seconds, the location where the mouse is working on the wheel is displaced by more than 30 pixels to the right from where it was working in the previous session.

This can be seen easily in the Dashboard http://192.168.240.50:8050/ (inside the SWC intranet).

Why is this happening?

**Comment by jkbhagatio** [comment]
Closing this as we haven't noticed this issue in any exp since exp0.2
