### ISSUE TITLE
Load blob tracking data for animal position when missing SLEAP data

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#400]
For parts of some experiments, e.g. the presocial periods, SLEAP data is not available.
Thus, currently, animal position data is not available for those presocial periods.

However, the animal position blob tracking data is always available, just not ingested. It's worth to note that the blob tracking data cannot reliably identify the different animals when more than one animal present (thus we should use SLEAP data).
But for single-animal time periods, this is a reasonable alternative.

The task here is to ingest blob tracking data whenever SLEAP data is not available, only for the periods of single-animal only

Tag @jkbhagatio and @OrsiFolsz here as well

**Comment by anayapouget** [comment]
We could also consider running full pose inference on pre and post social periods. This would be useful to Joaquin (he is currently just using some data in my personal ceph folders) and in general is would probably be good to have in order to be able to better compare individual and social sessions in analyses?

**Comment by ttngu207** [comment]
Thanks @anayapouget , yes, that would certainly solve this issue.
The question is whether we want to make this part of a formal process and to this in an automated manner. 
1. automatically triggers full pose analysis (send jobs to the clusters) on a per chunk (or per epoch?)
2. once the jobs are finished, copy the results to the `.../processed` folder

If it's a one off fix, we can certainly use your help to do this once. But if we want to include this step formally in the larger data processing/analysis flow, we should have another discussion to engineer this.

**Comment by jkbhagatio** [comment]
We've decided to go with the approach of adding a check to use centroid blob data for position ingestion if no sleap data, else will use sleap data (this includes data that would be in the processed dir if full pose inference is run on single animals)
