### ISSUE TITLE
Full pose sleap data for individual sessions

### ISSUE THREAD

**Issue by anayapouget** [SainsburyWellcomeCentre/aeon_mecha#404]
How do we want to run full pose inference on sessions where there is only one subject? 

We could drop using bonsai and only run the inference using sleap. At the end of inference we would have to open the file and assign the relevant ID to every skeleton. How would we want to retrieve the ID? User specified? Find it somewhere?

Or we could keep using bonsai which would be more consistent but would probably have to create a new bonsai workflow for that.

**Comment by glopesdev** [comment]
@anayapouget @jkbhagatio this is possibly also related to #418

**Comment by anayapouget** [comment]
Made a new bonsai workflow where the user specifies the ID of the mouse and you end up with similar bin files as those returned by the social full pose ID bonsai workflow. The identity likelihood value is manually set to np.nan since the id is user specified and the field does not apply. We discussed setting it to 1 but decided against it since sleap does not technically cap likelihoods at 1.
