### ISSUE TITLE
Clean up branch for sfn

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#428]
For accessing the example dataset during SfN, we are giving users access a clone of aeon_mecha with the example dataset and database, hosted on AWS at works.datajoint.com

We need to:

- [ ] Branch name
- [ ] Add notebooks to 'aeon/docs/examples'
- [ ] Clean up the branch (remove old notebooks / docs files that may confuse users)

Thanks @glopesdev !

**Comment by lochhh** [comment]
branch name suggestion: early-access

**Comment by lochhh** [comment]
closing as [done](https://github.com/SainsburyWellcomeCentre/aeon_mecha/tree/data-preview)
