### ISSUE TITLE
exp01_patchmovies.py in branch dev not working

### ISSUE THREAD

**Issue by joacorapela** [SainsburyWellcomeCentre/aeon_mecha#44]
(aeon_env) rapela@u237c:~/dev/research/gatsby-swc/fwg/repository/docs/examples(dev)$ python exp01_patchmovies.py 
BAA-1099793 on 2021-07-12 09:38:37.959969997...
Traceback (most recent call last):
  File "/nfs/ghome/live/rapela/dev/research/gatsby-swc/fwg/repository/docs/examples/exp01_patchmovies.py", line 69, in <module>
    in_patch1 = activepatch(wheel1, distp1 < patchradius, position)
TypeError: activepatch() takes 2 positional arguments but 3 were given

**Comment by jkbhagatio** [comment]
Closing this as deprecated code
