### ISSUE TITLE
There is a severe hardware failure 

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_mecha#58]
There is a severe hardware failure (run out of pellets, FED3 jammed, all cameras stopped working) at some point in the session but we notice that it happened only after a while and a large portion of the session may be affected.
Maybe user has to flag the session manually or can be automated

**Comment by jkbhagatio** [comment]
I believe this is now solved with our Alerts system - please re-open with explanation if not
