### ISSUE TITLE
Mouse is removed from the arena BEFORE we pressed stop

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_mecha#59]
Mouse is removed from the arena BEFORE we pressed stop: final part of the recording would contain us chasing the mouse and tracking errors. (Jai: catch experimenter in tracking, look for no objects (NaNs))
User needs to flag the session or maybe can be inferred from taking looking at tracking errors or area of tracked object

**Comment by jkbhagatio** [comment]
I'm tempted to label this as a "wontfix" and close this issue as we now follow a protocol where the experimenter should "Start Maintenance" before removing the mouse. 

@Dario55 what do you think? If you feel strongly about solving this issue another way, happy to reopen this issue and discuss.
