### ISSUE TITLE
Quantify delay between pellet delivery and pellet consumption

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_mecha#87]
Some numbers that will be key to have from the analysis of experiment zero data, before experiment 0.1, are the following:
1) time latency between when the threshold is crossed and when the command  deliver a pellet is sent (note that sometimes more then one of such command is sent)
2)time latency between when command is sent and IR beam is broken
3)time latency between when IR beam is broken and pellet is collected by the mouse 
4)Total distance on the wheel between when the threshold is crossed and the pellet is collected

Thank you.

**Comment by jkbhagatio** [comment]
Hi @lochhh , I know you have been working on this a bit - have you seen this issue and have you systematically looked at all 4 of these points Dario has made for exp 0.1, exp 0.2, and underground feeder data?
