### ISSUE TITLE
DataJoint - data ingestion of the 24/7 experiment (started on 2/23/2022)

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#88]
- [ ] Incorporate ingestion of per-acquisition-epoch config files (YAML) for 24/7 experiment
- [ ] Experiment meta info insertion (e.g. experiment name, experiment subjects, etc.)

**Comment by ttngu207** [comment]
Camera QC data computation
+ Is this running?
+ What is the qc output data directory (for exp0.1, it was `aeon/qc/experiment0.1`)

**Comment by ttngu207** [comment]
@glopesdev , how about we can let this run as a processing step in DataJoint pipeline?
Can you point me to this script. Is this ran on a per-epoch or per-chunk level?

**Comment by glopesdev** [comment]
@ttngu207 about metadata questions:
* the weight-scale does not seem to have a fixed sampling rate that we are aware of (or that we can easily access); on average it seems to do 20Hz, but it also has jitter around that;
* I can include the epoch_time in the metadata, for example using ISO-8601
* the serial numbers for patches and weight scale should be the COM port for now

> Could there be a change in revision without any changes to the devices' configurations (e.g. something else about the bonsai workflow?)

Yes, if the internal logic of the bonsai workflow changes, or if the script that exports metadata changes, or if any other calibration or anything at all changes, the revision will change

> Could there be a case where revision remains the same despite actual changes in devices' configuration for a particular epoch?

This shouldn't be possible as long as we only ever change configurations using the bonsai workflow. Of course there is always a large number of "hidden states" of system configuration that we don't/can't keep track in the repository (e.g. someone refocused or changed the zoom level of the camera mechanically, a faulty USB cable, windows update, memory replacements, etc).

> I could not find the position information for cameras and food_patches.

The final schema will include ROI in pixels for food patches, the nest, and also the position of the center of the arena, all in pixels. The position of the cameras is not included yet, as we need to develop the 3D reconstruction routine for this, which will include 6-DOF position (X,Y,Z) and rotation (X,Y,Z) information for each camera.

**Comment by glopesdev** [comment]
@ttngu207 I think it currently runs at the level of an entire dataset, but we can modify it to be parameterizable to either/both of these cases. In that case we should probably create an issue for it in aeon_mecha

**Comment by glopesdev** [comment]
@ttngu207 regarding ROI information, if it's easier I can include in the metadata export script a function that computes the centroid of each shape, if it is useful/easier to have a point that is considered the "position" of an ROI place

**Comment by glopesdev** [comment]
> Is there any issue with running this on a per-chunk level?

This won't be a problem, I will look into it and remake the script to make it more flexible.

**Comment by ttngu207** [comment]
> This won't be a problem, I will look into it and remake the script to make it more flexible.

Hi @glopesdev , I want to follow up on the progress of this script here. Do you have a draft I can take a look at, perhaps I can propose some prototype integration of this step into the dj pipeline. 
Currently this is a blocker for getting the position data ingested.
