### ISSUE TITLE
Mismatch in weight-scale folder and device name

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#90]
@glopesdev , @jkbhagatio 

Take the data in this epoch for example: /ceph/aeon/test2/experiment0.2/2022-03-01T23-36-39

The `Metadata.yml` specifies the weight-scale device to have the name `WeightNest`, while the corresponding data folder is named `Nest`. Due to this mismatch, calling the api to load weight measurement will return empty dataframe

```
api.weightdata("/ceph/aeon/test2/experiment0.2", device="WeightNest")

**Comment by ttngu207** [comment]
Hi @jkbhagatio , @glopesdev , just want to follow up on this issue

**Comment by jkbhagatio** [comment]
I believe this particular issue was fixed in the specified 'metadata.yml' file. Also as a fix going forward on the acquisition side, the device names in metadata.yml are now generated directly from the acquisition device names, so this type of mismatch should no longer be able to occur.
