### ISSUE TITLE
API load: ValueError: cannot reindex a non-unique index with a method or limit

### ISSUE THREAD

**Issue by lochhh** [SainsburyWellcomeCentre/aeon_mecha#99]
https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/3b2d00ea8d01b767518b2ab5ab22ea23f4d7304b/aeon/preprocess/api.py#L142

This happens when there are duplicated timestamps in the raw data file

**Comment by glopesdev** [comment]
In general these will be an error to handle during quality control steps, but we have also considered allowing them for specific features, for instance in the case of multi-animal tracking, where each unique frame timestamp would generate one row per animal. In this case, we could decide on a couple of options:
  * Create a multi-index with (timestamp, id)
  * Create one file per unique id

We should set aside some time to discuss as a group how to handle these cases and in general how to deal with duplicate timestamps for different streams.

**Comment by jkbhagatio** [comment]
We've solved this in #205
